version: '3'

services:
    json_server:
        image: node:latest
        working_dir: /json_server
        volumes:
        - ./json:/json_server
        command: bash script.sh
        ports: 
        - 8000:8000
        expose: 
        - 8000

    lite_server:
        image: node:latest
        working_dir: /lite_server
        volumes:
        - ./lite:/lite_server
        command: bash script.sh
        ports: 
        - 3000:3000
        expose:
        - 3000
        
    nginx:
        image: nginx
        ports:
        - "8080:80"
        environment:
        - NGINX_HOST=0.0.0.0
        - NGINX_PORT=80
        links: 
        - json_server
        - lite_server
